In [1]:
import numpy as np

In [7]:
arr1 = np.arange(1,13,2).reshape(2,3)
print(arr1)

[[ 1  3  5]
 [ 7  9 11]]


In [8]:
arr2= np.arange(2,14,2).reshape(2,3)
print(arr2)

[[ 2  4  6]
 [ 8 10 12]]


In [9]:
arr1+arr2

array([[ 3,  7, 11],
       [15, 19, 23]])

In [10]:
np.add(arr1,arr2)

array([[ 3,  7, 11],
       [15, 19, 23]])

In [16]:
np.subtract(arr1,arr2)
# print(arr1-arr2)

[[-1 -1 -1]
 [-1 -1 -1]]


In [17]:
np.divide(arr1,arr2)

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667]])

In [18]:
np.multiply(arr1,arr2)#for position to position multiply

array([[  2,  12,  30],
       [ 56,  90, 132]])

In [23]:
arr3 = np.arange(1,13,2).reshape(3,2)
arr1.dot(arr3) #matrix  multiplication

array([[ 61,  79],
       [151, 205]])

In [24]:
arr1 @ arr3

array([[ 61,  79],
       [151, 205]])

In [25]:
arr1.max

<function ndarray.max>

In [26]:
arr1.max()

11

In [30]:
arr1.argmax()+1

6

In [32]:
arr1.max(axis=1)

array([ 5, 11])

In [33]:
np.sum(arr1)#sum of elements of matrix

36

In [34]:
np.sum(arr1,axis=0)

array([ 8, 12, 16])

In [35]:
np.mean(arr1)

6.0

In [36]:
np.mean(arr1,axis=1)

array([3., 9.])

In [37]:
np.sqrt(arr1)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])