In [1]:
import numpy as np

In [2]:
ar = np.arange(0,16).reshape(4,4)
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [3]:
ar2=ar.reshape(1,-1)
print(ar2)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [4]:
ar2.ndim

2

In [5]:
ar3= ar.reshape(-1,1)
print(ar3)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [6]:
ar3.ndim

2

In [7]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
ar[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [9]:
a= np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [10]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [11]:
a[:,0]

array([ 0,  4,  8, 12])

In [12]:
a[0,:]

array([0, 1, 2, 3])

In [13]:
a.sum()

120

In [14]:
a[:,0].sum()

24

In [15]:
a.sum(axis=1)

array([ 6, 22, 38, 54])

In [16]:
a.sum(axis=0)

array([24, 28, 32, 36])

In [17]:
a[1].sum()

22

In [18]:
a.mean()

7.5

In [19]:
a @ ar

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

In [22]:
np.multiply(ar,a)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [23]:
a.dot(ar)

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

In [24]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [25]:
np.median(a)

7.5