# NumPy Functions

In [1]:
import numpy as np

# arange()

In [2]:
# np.arange(start, end ,steps)
ar = np.arange(1,13)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# ar = np.arange(1,13,3)
print(ar)

# linespace()

In [3]:
ar2 = np.linspace(1,5,4)
print(ar2)


[1.         2.33333333 3.66666667 5.        ]


# reshape

In [4]:
ar3=np.arange(1,13).reshape(2,3,2)
print(ar3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# revel()

In [5]:
#used for converting multidimentional to 1D
ar3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [6]:
ar3.flatten() #also pass arguments in paranthesis

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [7]:
ar3.transpose()

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])