In [1]:
import numpy as np

In [2]:
import random


In [6]:
np.random.random(6)

array([0.0700614 , 0.60671853, 0.89501018, 0.64098992, 0.52966617,
       0.40628853])

In [7]:
np.random.randint(1,100)

93

In [13]:
np.random.randint(5,6,(10,20))

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [17]:
c=np.array([1,2,3,4])
for i in range(16):
    print(np.random.permutation(c))

[1 3 2 4]
[2 1 4 3]
[1 2 3 4]
[1 2 4 3]
[2 1 4 3]
[4 1 3 2]
[4 2 1 3]
[1 3 2 4]
[1 2 4 3]
[1 4 2 3]
[2 3 1 4]
[4 1 3 2]
[3 2 4 1]
[2 4 1 3]
[3 1 2 4]
[1 2 3 4]
