In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndim

1

In [6]:
arr2 =np.array([[1,2,3],[1,2,3],[1,2,3]])
print(arr2)
arr2.ndim

[[1 2 3]
 [1 2 3]
 [1 2 3]]


2

In [7]:
arr2.size


9

In [8]:
arr2.shape

(3, 3)

In [9]:
arr.dtype

dtype('int32')